env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    github_token: "ENCRYPTED[!82ee7e07446c86fe97dda507543443a525fec83e693679c8f84d740764987310d74262013f45a1e5a56cc54e334e8f7c!]"
    bot_api: "ENCRYPTED[!10482e25ca82cf0efa74e4c474a9e5cb82c1b2e5545657dd1917cba34aa08ce880b37bef99a47d0a49c4bb48523144b9!]"
    chat_id: "ENCRYPTED[!c519abe30864df229179faa4e1eeaa0fde992d896ed620d45cb1f2ca25f0ee3b9373d08fb64a737c8759ae592ef9351c!]"

# store information about git here
    gmail: fire@gmail.com

task:
    name: fire
    timeout_in: 120m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    dl_plox: # To download cc in background
      - bash dl # cc download script
    clone_script:
      - bash clone
    flame_script:
      - bash redflame
    ul_plox: # Upload cc to cloud foreground
      - bash ul # cc uploading script
