env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    github_token: ""
    bot_api: "5540395322:AAHycGKaShVs-w5b2R99RphEXo6Dobhs9Zc"
    chat_id: "-1001624430991"

# store information about git here
    gmail: sqsa93103@gmail.com

# choose upload location (1:github_release 2:gdindex 3:github+gdindex both) default is gdrive
    upload_type: 3

task:
    name: aosp
    timeout_in: 260m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    download_ccache_background_script: # To download ccache in background
      - bash download_ccache # Ccache download script
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_ccache_script: # Upload ccache to cloud foreground
      - bash upload_ccache # Ccache uploading script
