#!/bin/bash
cd /tmp/rom # Depends on where source got synced
. /tmp/ci/function

# Normal build steps
. build/envsetup.sh
lunch rom_lavender-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 15G
ccache -o compression=true
ccache -z

# compile plox
make rom -j$(nproc --all) &
sleep 90m
kill %1
check_build_no && tg "Stop Compiling Rom To Collect Cache
Status: $progress | Build No: $build_no"

if [ -e out/target/product/$device_codename/*$device_codename*2022*zip ]; then

cd out/target/product/$device
send_zip=$(upload "*$device*2022*zip")
tg $id "Build Succeed!
$send_zip"

fi

ccache -s # Let's print ccache statistics finally
