#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h

. /tmp/ci/helper

install_apt

check_build_type
case "$build_type" in
		 V)
		 tg "Build Started! | Type : $build_type
Rom: $rom_name
Branch: $branch_name
Device: $device_codename
Status: $progress"
		 ;; # else
		 *)
		 tg "Started New Build as $rom_name isn't Compiled yet..!
Type : $build_type | Status: $progress"
esac

cd /tmp # Where to download cccahe

echo "• Downloading Cmf •"
down https://emy.ehteshammalik4.workers.dev/cirrus-user/$CIRRUS_REPO_OWNER/$device_codename/$rom_name/$branch_name/mf.tar.gz || down https://emy.ehteshammalik4.workers.dev/cirrus-user/$CIRRUS_REPO_OWNER/$device_codename/$rom_name/$branch_name/mf.tar.gz
if [ -e *.tar.gz ]; then
tg "$rom_name cmf downloaded successfully!
Total Size: $(ls -sh ${PWD}/mf.tar.gz | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"
else
tg "Skipping Cmf Download on 1st build..!"
fi

case "$build_type" in
		 C|c)
rm -rf *.tar.gz
esac

# Extract cmf so ci can use it
echo "• Extracting Cmf •"
if [ -e *.tar.gz ]; then
time tar xf *.tar.gz
fi

# Remove unnecessary downloaded file
rm -rf *.tar.gz

# fix
echo "" > /etc/mtab

# Start new build if system img compiled
case "$build_type" in
		 S|s)
		 echo "• build Type is System | Started loop•"
		 sleep 70m # start loop after 70mins
		 ;; # else
		 *) # skip the script
		 echo "• Build Type is not System | Skipped Script •"
		 exit 1
esac
while true; do
if [ -e /tmp/rom/out/target/product/$device_codename/system.img ]; then
echo "R" > /tmp/build_type.txt
tg "System Compilation completed! Starting mf upload
Status: $progress"
bash /tmp/ci/upload_cc
else
sleep 2m
fi
done&
