#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h

. /tmp/ci/function

apt install git

cd /tmp # Where to download cccahe

echo "• Cloning Gitlab Repo •"
git clone --depth=1 https://gitlab.com/$gitlab_username/$gitlab_reponame.git ccache
