#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h

. /tmp/ci/function

install_apt

check_build_type
case "$build_type" in
		 V)
		 tg "Build Started! | Type : $build_type
		 Status: $progress"
		 ;; # else
		 *)
		 tg "Started New Build as Rom isn't Compiled
		 Type : $build_type | Status: $progress"
esac

SECONDS=0

cd /tmp # Where to download cccahe

echo "• Cloning Gitlab Repo •"
git clone --depth=1 https://gitlab.com/$gitlab_username/$gitlab_reponame.git $rom_name
tg "Cache was Downloaded Successfully!
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

# Extract ccache so ci can use it
echo "• Extracting CCACHE •"
if [ -e $rom_name/*.tar.gz ]; then
mv $rom_name/*.tar.gz /tmp
time tar xf *.tar.gz
fi

# Remove unnecessary downloaded file
rm -rf *.tar.gz

# fix
echo "" > /etc/mtab
