#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
. /tmp/ci/function

SECONDS=0

# Sync with repo init command, -device,-mips,-darwin,-notdefault to save time and storage
repo init --depth=1 --no-repo-verify -u https://github.com/ROM/android_manifest -b 10 -g default,-mips,-darwin,-notdefault

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# local manifest
git clone --depth=1 https://github.com/$github_username/device_xiaomi_lavender -b x device/xiaomi/lavender
git clone --depth=1 https://github.com/$github_username/vendor_xiaomi_lavender -b x vendor/xiaomi/lavender
git clone --depth=1 https://github.com/$github_username/kernel_xiaomi_lavender -b x kernel/xiaomi/lavender

check_build_no && tg "Cloned all Sources Successfully!
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress | Build No: $build_no"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
