#!/bin/bash

cd /tmp
. /tmp/ci/function

# Abort if already executed
if [ ! -e /tmp/abort.txt ]; then

# compress in with pigz in a single zip.
com ccache 0

echo "• Uploading Cache On Gdrive •"
upload_ccache ccache.tar.gz
tg "Cache was Uploaded Successfully!
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress | cache zip: $url"

rom_zip=`ls out/target/product/$device_codename/*$device_codename*2022*zip`
if [ ! -e $rom_zip ]; then

# update build type for next build
build_type="`cat /tmp/build_type.txt`"

# lets compile again as rom isn't ready yet
git clone -b $CIRRUS_BRANCH $github_repo $rom_name && cd $rom_name
git commit -sm "SH*T, HERE WE GO AGAIN | $build_type
* Empty Commit To Re-Start The Build" --allow-empty
git push -f

else

# drop empty commits
git clone -b $CIRRUS_BRANCH $github_repo $rom_name && cd $rom_name
git filter-branch --commit-filter 'git_commit_non_empty_tree "$@"' -f HEAD
git push -f

fi

echo "dont upload cache again" > /tmp/abort.txt

fi

# clean storage except ci files
rm -rf /tmp/rom
rm -rf /tmp/cache
